//! Product-facing swap terms shared by quote, relayer, and UI code.
//!
//! The protocol always settles through the Starknet `AtomicLock`, but the user
//! journey can run in either direction. Keep the direction explicit so API and
//! frontend code do not infer roles from token names or amounts.

use serde::{Deserialize, Deserializer, Serialize, Serializer};
use std::str::FromStr;
use thiserror::Error;

pub const MIN_LOCK_DURATION_SECS: u64 = 3 * 60 * 60;
pub const DEFAULT_MONERO_CONFIRMATIONS: u64 = 10;

fn serialize_u128_as_string<S>(value: &u128, serializer: S) -> Result<S::Ok, S::Error>
where
    S: Serializer,
{
    serializer.serialize_str(&value.to_string())
}

fn deserialize_u128_from_string<'de, D>(deserializer: D) -> Result<u128, D::Error>
where
    D: Deserializer<'de>,
{
    let s = String::deserialize(deserializer)?;
    s.parse::<u128>().map_err(serde::de::Error::custom)
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum Chain {
    Monero,
    Starknet,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum MoneroNetwork {
    Mainnet,
    Stagenet,
    Testnet,
}

impl FromStr for MoneroNetwork {
    type Err = SwapTermParseError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match normalized(value).as_str() {
            "mainnet" => Ok(Self::Mainnet),
            "stagenet" => Ok(Self::Stagenet),
            "testnet" => Ok(Self::Testnet),
            _ => Err(SwapTermParseError::InvalidMoneroNetwork(value.to_string())),
        }
    }
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum StarknetReceiveMode {
    PublicAddress,
    PrivacyOpenNote,
}

impl Default for StarknetReceiveMode {
    fn default() -> Self {
        Self::PublicAddress
    }
}

impl FromStr for StarknetReceiveMode {
    type Err = SwapTermParseError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match normalized(value).as_str() {
            "public_address" | "public" => Ok(Self::PublicAddress),
            "privacy_open_note" | "private" | "privacy" => Ok(Self::PrivacyOpenNote),
            _ => Err(SwapTermParseError::InvalidStarknetReceiveMode(
                value.to_string(),
            )),
        }
    }
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum SwapDirection {
    /// User sends XMR and receives a Starknet token claim.
    XmrToStarknet,
    /// User locks a Starknet token and receives XMR.
    StarknetToXmr,
}

impl FromStr for SwapDirection {
    type Err = SwapTermParseError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match normalized(value).as_str() {
            "xmr_to_starknet" | "monero_to_starknet" => Ok(Self::XmrToStarknet),
            "starknet_to_xmr" | "starknet_to_monero" => Ok(Self::StarknetToXmr),
            _ => Err(SwapTermParseError::InvalidDirection(value.to_string())),
        }
    }
}

impl SwapDirection {
    pub fn user_sends(self) -> Chain {
        match self {
            Self::XmrToStarknet => Chain::Monero,
            Self::StarknetToXmr => Chain::Starknet,
        }
    }

    pub fn user_receives(self) -> Chain {
        match self {
            Self::XmrToStarknet => Chain::Starknet,
            Self::StarknetToXmr => Chain::Monero,
        }
    }

    pub fn user_receives_starknet_claim(self) -> bool {
        matches!(self, Self::XmrToStarknet)
    }

    pub fn user_receives_monero_claim(self) -> bool {
        matches!(self, Self::StarknetToXmr)
    }
}

fn normalized(value: &str) -> String {
    value.trim().to_ascii_lowercase().replace('-', "_")
}

fn valid_hex_felt(value: &str) -> bool {
    let Some(hex) = value.trim().strip_prefix("0x") else {
        return false;
    };
    !hex.is_empty() && hex.len() <= 64 && hex.chars().all(|ch| ch.is_ascii_hexdigit())
}

fn normalized_felt_hex(value: &str) -> String {
    let hex = value
        .trim()
        .strip_prefix("0x")
        .unwrap_or(value.trim())
        .trim_start_matches('0')
        .to_ascii_lowercase();
    if hex.is_empty() {
        "0".to_string()
    } else {
        hex
    }
}

fn same_felt_hex(left: &str, right: &str) -> bool {
    normalized_felt_hex(left) == normalized_felt_hex(right)
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct StarknetPrivacySettlement {
    /// StarkWare privacy pool contract that will call the helper via
    /// `InvokeExternal`.
    pub privacy_pool_address: String,
    /// Atomic swap helper that reveals, claims, approves the pool, and returns
    /// `OpenNoteDeposit`.
    pub privacy_helper_address: String,
    /// Open note id generated by the privacy-pool SDK for the receiving user.
    pub open_note_id: String,
    /// Token expected in the open note. Must match `SwapTerms.starknet_token`.
    pub open_note_token: String,
    #[serde(
        serialize_with = "serialize_u128_as_string",
        deserialize_with = "deserialize_u128_from_string"
    )]
    pub open_note_amount: u128,
}

impl StarknetPrivacySettlement {
    fn validate_against(&self, terms: &SwapTerms) -> Result<(), SwapTermsError> {
        if !valid_hex_felt(&self.privacy_pool_address) {
            return Err(SwapTermsError::InvalidPrivacyPoolAddress);
        }
        if !valid_hex_felt(&self.privacy_helper_address) {
            return Err(SwapTermsError::InvalidPrivacyHelperAddress);
        }
        if !valid_hex_felt(&self.open_note_id) || normalized_felt_hex(&self.open_note_id) == "0" {
            return Err(SwapTermsError::InvalidPrivacyOpenNoteId);
        }
        if !valid_hex_felt(&self.open_note_token) {
            return Err(SwapTermsError::InvalidPrivacyOpenNoteToken);
        }
        if !same_felt_hex(&self.open_note_token, &terms.starknet_token) {
            return Err(SwapTermsError::PrivacyOpenNoteTokenMismatch);
        }
        if self.open_note_amount != terms.starknet_amount {
            return Err(SwapTermsError::PrivacyOpenNoteAmountMismatch);
        }
        Ok(())
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct SwapTerms {
    pub swap_id: String,
    pub direction: SwapDirection,
    pub monero_network: MoneroNetwork,
    pub monero_amount_piconero: u64,
    #[serde(
        serialize_with = "serialize_u128_as_string",
        deserialize_with = "deserialize_u128_from_string"
    )]
    pub starknet_amount: u128,
    pub starknet_token: String,
    pub lock_duration_secs: u64,
    pub monero_confirmations: u64,
    #[serde(default)]
    pub starknet_receive_mode: StarknetReceiveMode,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub starknet_privacy_settlement: Option<StarknetPrivacySettlement>,
}

impl SwapTerms {
    pub fn validate(&self) -> Result<(), SwapTermsError> {
        if self.swap_id.trim().is_empty() {
            return Err(SwapTermsError::MissingSwapId);
        }
        if self.monero_amount_piconero == 0 {
            return Err(SwapTermsError::ZeroMoneroAmount);
        }
        if self.starknet_amount == 0 {
            return Err(SwapTermsError::ZeroStarknetAmount);
        }
        if self.lock_duration_secs < MIN_LOCK_DURATION_SECS {
            return Err(SwapTermsError::LockDurationTooShort {
                actual: self.lock_duration_secs,
                minimum: MIN_LOCK_DURATION_SECS,
            });
        }
        if self.monero_confirmations < DEFAULT_MONERO_CONFIRMATIONS {
            return Err(SwapTermsError::InsufficientMoneroConfirmations {
                actual: self.monero_confirmations,
                minimum: DEFAULT_MONERO_CONFIRMATIONS,
            });
        }
        if !self.starknet_token.starts_with("0x") || self.starknet_token.len() <= 2 {
            return Err(SwapTermsError::InvalidStarknetToken);
        }
        match (
            self.direction,
            self.starknet_receive_mode,
            self.starknet_privacy_settlement.as_ref(),
        ) {
            (
                SwapDirection::XmrToStarknet,
                StarknetReceiveMode::PrivacyOpenNote,
                Some(settlement),
            ) => settlement.validate_against(self)?,
            (SwapDirection::XmrToStarknet, StarknetReceiveMode::PrivacyOpenNote, None) => {
                return Err(SwapTermsError::MissingStarknetPrivacySettlement);
            }
            (_, StarknetReceiveMode::PrivacyOpenNote, _) => {
                return Err(SwapTermsError::PrivacyReceiveModeRequiresXmrToStarknet);
            }
            (_, StarknetReceiveMode::PublicAddress, Some(_)) => {
                return Err(SwapTermsError::UnexpectedStarknetPrivacySettlement);
            }
            (_, StarknetReceiveMode::PublicAddress, None) => {}
        }
        Ok(())
    }
}

#[derive(Debug, Error, PartialEq, Eq)]
pub enum SwapTermParseError {
    #[error("invalid swap direction: {0}")]
    InvalidDirection(String),
    #[error("invalid monero network: {0}")]
    InvalidMoneroNetwork(String),
    #[error("invalid starknet receive mode: {0}")]
    InvalidStarknetReceiveMode(String),
}

#[derive(Debug, Error, PartialEq, Eq)]
pub enum SwapTermsError {
    #[error("swap_id is required")]
    MissingSwapId,
    #[error("monero amount must be non-zero")]
    ZeroMoneroAmount,
    #[error("starknet amount must be non-zero")]
    ZeroStarknetAmount,
    #[error("lock duration {actual}s is shorter than minimum {minimum}s")]
    LockDurationTooShort { actual: u64, minimum: u64 },
    #[error("monero confirmations {actual} is lower than minimum {minimum}")]
    InsufficientMoneroConfirmations { actual: u64, minimum: u64 },
    #[error("starknet token must be a non-empty 0x-prefixed address")]
    InvalidStarknetToken,
    #[error("privacy receive mode is only valid for xmr_to_starknet")]
    PrivacyReceiveModeRequiresXmrToStarknet,
    #[error("privacy_open_note requires starknet_privacy_settlement")]
    MissingStarknetPrivacySettlement,
    #[error("public Starknet settlement must not include starknet_privacy_settlement")]
    UnexpectedStarknetPrivacySettlement,
    #[error("privacy pool must be a non-empty 0x-prefixed felt/address")]
    InvalidPrivacyPoolAddress,
    #[error("privacy helper must be a non-empty 0x-prefixed felt/address")]
    InvalidPrivacyHelperAddress,
    #[error("open note id must be a non-zero 0x-prefixed felt")]
    InvalidPrivacyOpenNoteId,
    #[error("open note token must be a non-empty 0x-prefixed felt/address")]
    InvalidPrivacyOpenNoteToken,
    #[error("open note token must match the Starknet swap token")]
    PrivacyOpenNoteTokenMismatch,
    #[error("open note amount must match the Starknet swap amount")]
    PrivacyOpenNoteAmountMismatch,
}
