/// Step-by-step constructor flow test to isolate where the error occurs
/// This mimics the exact constructor flow but with validation after each step

#[cfg(test)]
mod constructor_step_by_step_tests {
    use atomic_lock::poseidon_challenge::compute_dleq_challenge_poseidon;
    use core::array::ArrayTrait;
    use core::integer::u256;
    use garaga::signatures::eddsa_25519::decompress_edwards_pt_from_y_compressed_le_into_weirstrass_point;
    use garaga::ec_ops::{msm_g1, G1PointTrait};
    use garaga::definitions::get_G;
    use atomic_lock::AtomicLock::reduce_felt_to_scalar;
    // Constants from rust/test_vectors.json (match test_vectors.cairo)
    const TESTVECTOR_G_COMPRESSED: u256 = u256 {
        low: 0x66666666666666666666666666666658,
        high: 0x66666666666666666666666666666666,
    };
    const TESTVECTOR_Y_COMPRESSED: u256 = u256 {
        low: 0x21ba32594950b67cf0d8bb8c8ac5e8c7,
        high: 0xf08df421a3209ab6373dd0ec7ef25dfd,
    };
    const TESTVECTOR_Y_SQRT_HINT: u256 = u256 {
        low: 0x928f238c602cdbb49c96ac47cbbf79d7,
        high: 0x65c31da8af8318232d04a1abf99f036e,
    };
    const TESTVECTOR_T_COMPRESSED: u256 = u256 {
        low: 0x54e86953e7cc99b545cfef03f63cce85,
        high: 0x427dde0adb325f957d29ad71e4643882,
    };
    const TESTVECTOR_U_COMPRESSED: u256 = u256 {
        low: 0x9244eb3a3699efed3106c6ae0afdf28,
        high: 0xb6e0bfc0d9fbb8a4c8ef08cb5da2eff3,
    };
    const TESTVECTOR_R1_COMPRESSED: u256 = u256 {
        low: 0x3cb02521d7a17fedca11c02ea41fe334,
        high: 0x11ef09256f90d942ca7a0e4ae05926a5,
    };
    const TESTVECTOR_R2_COMPRESSED: u256 = u256 {
        low: 0xe66ca975ef303c032fcc18a952325162,
        high: 0xc5d2eb608176c8b79dfa55289c35b35f,
    };
    const ED25519_ORDER: u256 = u256 {
        low: 0x14def9dea2f79cd65812631a5cf5d3ed,
        high: 0x10000000000000000000000000000000,
    };

    const ED25519_CURVE_INDEX: u32 = 4;

    // Use constants from single source of truth (test_vectors.cairo)
    // Sqrt hints (generated by fix_hints.py)
    const TEST_ADAPTOR_POINT_SQRT_HINT: u256 = u256 {
        low: 0x448c18dcf34127e112ff945a65defbfc,
        high: 0x17611da35f39a2a5e3a9fddb8d978e4f,
    };
    const TEST_SECOND_POINT_SQRT_HINT: u256 = u256 {
        low: 0xcffea6b3bffe746de20fdd0734b30845,
        high: 0x5e4a3b18b41199f9389ded8696067271,
    };
    const TEST_R1_SQRT_HINT: u256 = u256 {
        low: 0x623d9789d855bcc4f0fbd8683b350688,
        high: 0x0a2d15cdfbfcf6181e92f0b7c74b477e,
    };
    const TEST_R2_SQRT_HINT: u256 = u256 {
        low: 0xd8b08d5ec3d265b83e5e333d750d6b37,
        high: 0x0e41fbdbbf62b47c511e0a5aa04059de,
    };
    // Use constants from single source of truth (test_vectors.cairo)
    // CRITICAL: Use ORIGINAL SHA-256 big-endian words (not pre-swapped)
    // hashlock_to_u256() will byte-swap them - test constants should NOT be pre-swapped
    const RESPONSE: u256 = u256 {
        low: 0xbe3ffdd10e06b50b800feb45877b787b,
        high: 0x2f0ceba8a8c56d6f6b4ed3ae98db234,
    };
    const CHALLENGE_FELT: felt252 = 0x47c760eb9b6a8797680bef6218e06aacc6570f8be11819d2268bb024f816108;

    fn get_test_dleq_response() -> u256 {
        RESPONSE
    }

    fn get_real_msm_hints() -> (Span<felt252>, Span<felt252>, Span<felt252>, Span<felt252>) {
        let s_hint_for_g = array![
            0xceeec4a90f34e45c033e2ff5,
            0xb419479f38f86b2b114d2ff1,
            0x256941d7d54e7beb,
            0x0,
            0xaa6ddc025eb012317a89612a,
            0x6e9d804e52cb98594f552df2,
            0x47244d9888c072a3,
            0x0,
            0xcd234e4105b9809a3f4f0dde019dac1,
            0x1268c27967bf37239a1bdcad1722144e1
        ].span();
        let s_hint_for_y = array![
            0x872011d1a9f20fc5fbed65ec,
            0xd36e4710d58461cfe9c9ee1d,
            0x686f29bbaf2b952f,
            0x0,
            0xf350a6f8bc8acbb1d5c40cd5,
            0x4b256a3dba76a0bc779c811,
            0x43f41814a3eefa59,
            0x0,
            0xcd234e4105b9809a3f4f0dde019dac1,
            0x1268c27967bf37239a1bdcad1722144e1
        ].span();
        let c_neg_hint_for_t = array![
            0xfbeb7a88a7204a3109847933,
            0xd7bd766f54592bfb04b8a0bf,
            0x36adfbd5b292a10e,
            0x0,
            0xb1cb68d66c0170146df52bb2,
            0x7ad50b1ffcd1293f12940e01,
            0x665e063c6d4ac0f6,
            0x0,
            0x4d5cf08f2a0aee991f621d5e4e15728,
            0x1148705832ba97f2b70dec32979f4f785
        ].span();
        let c_neg_hint_for_u = array![
            0x16ecdc108960cb810ed61451,
            0x28bf80201d67e2f4728ba74b,
            0x63f872f4f71e1950,
            0x0,
            0xe94caf1beb68a19f34eb98a4,
            0x48bcbcb46602eeea1b043d0d,
            0x52e390f474357096,
            0x0,
            0x4d5cf08f2a0aee991f621d5e4e15728,
            0x1148705832ba97f2b70dec32979f4f785
        ].span();
        (s_hint_for_g, s_hint_for_y, c_neg_hint_for_t, c_neg_hint_for_u)
    }

    #[test]
    fn test_step1_decompress_all_points() {
        // Step 1: Decompress all 4 points (matching constructor)
        let adaptor_result = decompress_edwards_pt_from_y_compressed_le_into_weirstrass_point(
            TESTVECTOR_T_COMPRESSED,
            TEST_ADAPTOR_POINT_SQRT_HINT
        );
        assert(adaptor_result.is_some(), 'Step 1a: adaptor decompress');
        let adaptor = adaptor_result.unwrap();
        adaptor.assert_on_curve_excluding_infinity(ED25519_CURVE_INDEX);

        let second_result = decompress_edwards_pt_from_y_compressed_le_into_weirstrass_point(
            TESTVECTOR_U_COMPRESSED,
            TEST_SECOND_POINT_SQRT_HINT
        );
        assert(second_result.is_some(), 'Step 1b: second decompress');
        let second = second_result.unwrap();
        second.assert_on_curve_excluding_infinity(ED25519_CURVE_INDEX);

        let r1_result = decompress_edwards_pt_from_y_compressed_le_into_weirstrass_point(
            TESTVECTOR_R1_COMPRESSED,
            TEST_R1_SQRT_HINT
        );
        assert(r1_result.is_some(), 'Step 1c: R1 decompress');
        let r1 = r1_result.unwrap();
        r1.assert_on_curve_excluding_infinity(ED25519_CURVE_INDEX);

        let r2_result = decompress_edwards_pt_from_y_compressed_le_into_weirstrass_point(
            TESTVECTOR_R2_COMPRESSED,
            TEST_R2_SQRT_HINT
        );
        assert(r2_result.is_some(), 'Step 1d: R2 decompress');
        let r2 = r2_result.unwrap();
        r2.assert_on_curve_excluding_infinity(ED25519_CURVE_INDEX);

        // All points decompressed successfully
        assert(true, 'Step 1: All points OK');
    }

    #[test]
    fn test_step2_compute_challenge() {
        // Step 2: Compute challenge (matching constructor)
        let hashlock = array![
            0xb6acca81_u32, 0xa0939a85_u32, 0x6c35e4c4_u32, 0x188e95b9_u32,
            0x1731aab1_u32, 0xd4629a4c_u32, 0xee79dd09_u32, 0xded4fc94_u32
        ].span();
        let challenge = compute_dleq_challenge_poseidon(
            TESTVECTOR_G_COMPRESSED,
            TESTVECTOR_Y_COMPRESSED,
            TESTVECTOR_T_COMPRESSED,
            TESTVECTOR_U_COMPRESSED,
            TESTVECTOR_R1_COMPRESSED,
            TESTVECTOR_R2_COMPRESSED,
            hashlock,
            ED25519_ORDER,
        );
        // Challenge computed successfully (just verify it's non-zero)
        assert(challenge != 0, 'Step 2: Challenge computed');
    }

    #[test]
    fn test_step3a_msm_sg_only() {
        // Isolate: Test only s·G MSM call
        // Use EXACT same approach as test_garaga_msm_all_calls (which works)
        let G = get_G(ED25519_CURVE_INDEX);
        // Use direct full scalar (matching working test)
        let s_scalar = RESPONSE;
        // Use hardcoded hint (matching test_garaga_msm_all_calls which works)
        let s_hint_for_g = array![
            0xceeec4a90f34e45c033e2ff5,
            0xb419479f38f86b2b114d2ff1,
            0x256941d7d54e7beb,
            0x0,
            0xaa6ddc025eb012317a89612a,
            0x6e9d804e52cb98594f552df2,
            0x47244d9888c072a3,
            0x0,
            0xcd234e4105b9809a3f4f0dde019dac1,
            0x1268c27967bf37239a1bdcad1722144e1
        ].span();
        
        let sG = msm_g1(
            array![G].span(),
            array![s_scalar].span(),
            ED25519_CURVE_INDEX,
            s_hint_for_g
        );
        sG.assert_on_curve_excluding_infinity(ED25519_CURVE_INDEX);
        assert(true, 'Step 3a: sG OK');
    }

    #[test]
    fn test_step3b_msm_negct_only() {
        // Isolate: Test only (-c)·T MSM call
        let adaptor = decompress_edwards_pt_from_y_compressed_le_into_weirstrass_point(
            TESTVECTOR_T_COMPRESSED,
            TEST_ADAPTOR_POINT_SQRT_HINT
        ).unwrap();
        let challenge = CHALLENGE_FELT;
        let c_scalar = reduce_felt_to_scalar(challenge);
        let c_neg_scalar = (ED25519_ORDER - (c_scalar % ED25519_ORDER)) % ED25519_ORDER;
        let (_, _, c_neg_hint_for_t, _) = get_real_msm_hints();
        
        let neg_cT = msm_g1(
            array![adaptor].span(),
            array![c_neg_scalar].span(),
            ED25519_CURVE_INDEX,
            c_neg_hint_for_t
        );
        neg_cT.assert_on_curve_excluding_infinity(ED25519_CURVE_INDEX);
        assert(true, 'Step 3b: -cT OK');
    }

    #[test]
    fn test_step3c_msm_sy_only() {
        // Isolate: Test only s·Y MSM call
        // Use EXACT same approach as test_garaga_msm_all_calls (which works)
        let Y = decompress_edwards_pt_from_y_compressed_le_into_weirstrass_point(
            TESTVECTOR_Y_COMPRESSED,
            TESTVECTOR_Y_SQRT_HINT
        ).unwrap();
        // Use direct full scalar (matching working test)
        let s_scalar = RESPONSE;
        // Use hardcoded hint (matching test_garaga_msm_all_calls which works)
        let s_hint_for_y = array![
            0x872011d1a9f20fc5fbed65ec,
            0xd36e4710d58461cfe9c9ee1d,
            0x686f29bbaf2b952f,
            0x0,
            0xf350a6f8bc8acbb1d5c40cd5,
            0x4b256a3dba76a0bc779c811,
            0x43f41814a3eefa59,
            0x0,
            0xcd234e4105b9809a3f4f0dde019dac1,
            0x1268c27967bf37239a1bdcad1722144e1
        ].span();
        
        let sY = msm_g1(
            array![Y].span(),
            array![s_scalar].span(),
            ED25519_CURVE_INDEX,
            s_hint_for_y
        );
        sY.assert_on_curve_excluding_infinity(ED25519_CURVE_INDEX);
        assert(true, 'Step 3c: sY OK');
    }

    #[test]
    fn test_step3d_msm_negcu_only() {
        // Isolate: Test only (-c)·U MSM call
        let second = decompress_edwards_pt_from_y_compressed_le_into_weirstrass_point(
            TESTVECTOR_U_COMPRESSED,
            TEST_SECOND_POINT_SQRT_HINT
        ).unwrap();
        let challenge = CHALLENGE_FELT;
        let c_scalar = reduce_felt_to_scalar(challenge);
        let c_neg_scalar = (ED25519_ORDER - (c_scalar % ED25519_ORDER)) % ED25519_ORDER;
        let (_, _, _, c_neg_hint_for_u) = get_real_msm_hints();
        
        let neg_cU = msm_g1(
            array![second].span(),
            array![c_neg_scalar].span(),
            ED25519_CURVE_INDEX,
            c_neg_hint_for_u
        );
        neg_cU.assert_on_curve_excluding_infinity(ED25519_CURVE_INDEX);
        assert(true, 'Step 3d: -cU OK');
    }

    #[test]
    fn test_step3_all_msm_calls() {
        // Step 3: Execute all MSM calls in sequence (matching _verify_dleq_proof)
        // Decompress points (restored - needed for correct hints)
        let adaptor = decompress_edwards_pt_from_y_compressed_le_into_weirstrass_point(
            TESTVECTOR_T_COMPRESSED,
            TEST_ADAPTOR_POINT_SQRT_HINT
        ).unwrap();
        let second = decompress_edwards_pt_from_y_compressed_le_into_weirstrass_point(
            TESTVECTOR_U_COMPRESSED,
            TEST_SECOND_POINT_SQRT_HINT
        ).unwrap();

        // Get base points
        let G = get_G(ED25519_CURVE_INDEX);
        let Y = decompress_edwards_pt_from_y_compressed_le_into_weirstrass_point(
            TESTVECTOR_Y_COMPRESSED,
            TESTVECTOR_Y_SQRT_HINT
        ).unwrap();

        // FIXED: Use direct scalar construction (proven to work)
        // reduce_felt_to_scalar() fails in sequential context for unknown reason
        // Direct construction avoids the issue and matches working individual tests
        let s_scalar = RESPONSE;
        let c_scalar = reduce_felt_to_scalar(CHALLENGE_FELT);
        let c_neg_scalar = (ED25519_ORDER - (c_scalar % ED25519_ORDER)) % ED25519_ORDER;

        // TEST: Use hardcoded hints instead of get_real_msm_hints()
        // This will tell us if get_real_msm_hints() is causing span corruption
        let s_hint_for_g = array![
            0xceeec4a90f34e45c033e2ff5,
            0xb419479f38f86b2b114d2ff1,
            0x256941d7d54e7beb,
            0x0,
            0xaa6ddc025eb012317a89612a,
            0x6e9d804e52cb98594f552df2,
            0x47244d9888c072a3,
            0x0,
            0xcd234e4105b9809a3f4f0dde019dac1,
            0x1268c27967bf37239a1bdcad1722144e1
        ].span();
        let s_hint_for_y = array![
            0x872011d1a9f20fc5fbed65ec,
            0xd36e4710d58461cfe9c9ee1d,
            0x686f29bbaf2b952f,
            0x0,
            0xf350a6f8bc8acbb1d5c40cd5,
            0x4b256a3dba76a0bc779c811,
            0x43f41814a3eefa59,
            0x0,
            0xcd234e4105b9809a3f4f0dde019dac1,
            0x1268c27967bf37239a1bdcad1722144e1
        ].span();
        let c_neg_hint_for_t = array![
            0xfbeb7a88a7204a3109847933,
            0xd7bd766f54592bfb04b8a0bf,
            0x36adfbd5b292a10e,
            0x0,
            0xb1cb68d66c0170146df52bb2,
            0x7ad50b1ffcd1293f12940e01,
            0x665e063c6d4ac0f6,
            0x0,
            0x4d5cf08f2a0aee991f621d5e4e15728,
            0x1148705832ba97f2b70dec32979f4f785
        ].span();
        let c_neg_hint_for_u = array![
            0x16ecdc108960cb810ed61451,
            0x28bf80201d67e2f4728ba74b,
            0x63f872f4f71e1950,
            0x0,
            0xe94caf1beb68a19f34eb98a4,
            0x48bcbcb46602eeea1b043d0d,
            0x52e390f474357096,
            0x0,
            0x4d5cf08f2a0aee991f621d5e4e15728,
            0x1148705832ba97f2b70dec32979f4f785
        ].span();

        // MSM call 1: s·G
        assert(true, 'Before MSM 1');
        let sG = msm_g1(
            array![G].span(),
            array![s_scalar].span(),
            ED25519_CURVE_INDEX,
            s_hint_for_g
        );
        assert(true, 'After MSM 1');
        sG.assert_on_curve_excluding_infinity(ED25519_CURVE_INDEX);
        assert(true, 'Step 3a: sG OK');

        // MSM call 2: (-c)·T
        assert(true, 'Before MSM 2');
        let neg_cT = msm_g1(
            array![adaptor].span(),
            array![c_neg_scalar].span(),
            ED25519_CURVE_INDEX,
            c_neg_hint_for_t
        );
        assert(true, 'After MSM 2');
        neg_cT.assert_on_curve_excluding_infinity(ED25519_CURVE_INDEX);
        assert(true, 'Step 3b: -cT OK');

        // MSM call 3: s·Y
        assert(true, 'Before MSM 3');
        let sY = msm_g1(
            array![Y].span(),
            array![s_scalar].span(),
            ED25519_CURVE_INDEX,
            s_hint_for_y
        );
        assert(true, 'After MSM 3');
        sY.assert_on_curve_excluding_infinity(ED25519_CURVE_INDEX);
        assert(true, 'Step 3c: sY OK');

        // MSM call 4: (-c)·U
        assert(true, 'Before MSM 4');
        let neg_cU = msm_g1(
            array![second].span(),
            array![c_neg_scalar].span(),
            ED25519_CURVE_INDEX,
            c_neg_hint_for_u
        );
        assert(true, 'After MSM 4');
        neg_cU.assert_on_curve_excluding_infinity(ED25519_CURVE_INDEX);
        assert(true, 'Step 3d: -cU OK');

        // All MSM calls succeeded
        assert(true, 'Step 3: All MSM OK');
    }

}
